version: "3.7"

services:
  db:
    container_name: transcendence-db
    image: postgres
    restart: on-failure
    env_file:
      - "./backend/.env"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  backend:
    container_name: transcendence-backend
    build:
      context: backend
    depends_on: [db, minio, redis]
    restart: on-failure

  frontend:
    container_name: transcendence-frontend
    build:
      context: frontend
    depends_on: [backend]
  redis:
    container_name: transcendence-redis
    image: redis
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    container_name: minio-storage
    ports:
      - "9001:9001"
      - "9000:9000" # for the minio api
    env_file:
      - "./backend/.env"
    command: 'server /data --console-address ":9001"'
    restart: on-failure
    volumes:
      - "minio-data:/data"

  server:
    image: nginx
    container_name: transcendence-nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on: [backend]

volumes:
  minio-data:
  redis-data:
  db-data:
